name: Flask App CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
     # env:
      #  AGENT_TOOLSDIRECTORY: /opt/hostedtoolache
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        
    - name: Build and Test Flask App
      run: |
        flask run --host=0.0.0.0 --port=5003 
        #&
        #sleep 5 # wait for Flask app to start
        #curl http://localhost:5002
